[package]
name = "rnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
rustls = { version = "0.20.2", features = ["dangerous_configuration", "quic"] }
quinn = "0.8.0"
rcgen = "0.8.14"
futures = "0.3.19"
bytes = "1.1.0"
bitflags = "1.3.2"
parking_lot = "0.12.0"
log = "0.4.14"
async-trait = "0.1.52"

[dev-dependencies]
env_logger = "0.9.0"
