[package]
name = "rnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
tokio-serde = { version = "0.8.0", features = ["bincode"] }
futures = "0.3.19"

rustls = { version = "0.20.2", features = ["dangerous_configuration", "quic"] }
quinn = "0.8.0"
rcgen = "0.9.0"

bitflags = "1.3.2"
parking_lot = "0.12.0"
log = "0.4.14"

bytes = { version = "1.1.0", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
bincode = { version = "2.0.0-beta.2", features = ["serde"] }
anyhow = "1.0.53"

[dev-dependencies]
env_logger = "0.9.0"
